spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost/woh
    username: woh
    password: qwerty
    initialization-mode: never
  session:
    store-type: mongodb
  data:
    mongodb:
      uri: mongodb://localhost/woh

---

spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: never
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}/${MONGO_DB}
