spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    show-sql: ${SHOW_SQL}
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: never
  session:
    store-type: mongodb
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
      grid-fs-database: ${MONGO_DB}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: ${ERROR_LEVEL}
      hibernate: ${ERROR_LEVEL}

parser:
  host: ${PARSER_HOST}
  port: ${PARSER_PORT}
