spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/woh?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
    username: woh
    password: qwerty
    initialization-mode: never
  session:
    store-type: mongodb
  data:
    mongodb:
      host: localhost
      database: woh
      grid-fs-database: woh
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG

parser:
  host: localhost
  port: 3000

---

spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: never
  data:
    mongodb:
      host: ${MONGO_HOST}
      database: ${MONGO_DB}
      grid-fs-database: ${MONGO_DB}
  jpa:
    show-sql: false

logging:
  level:
    org:
      springframework:
        web: ERROR
      hibernate: ERROR

parser:
  host: ${PARSER_HOST}
  port: ${PARSER_PORT}
